language: ruby
rvm:
  - 2.5.0
  - 2.4.0
  - 2.4.0-rc1
  - 2.4.0-preview3
  - 2.4.0-preview3-clang
  - 2.4.0-preview2
  - 2.4.0-preview2-clang
  - 2.4.0-preview1
  - 2.4.0-preview1-clang
  - 2.3.8
  - 2.3.7
  - 2.3.6
  - 2.3.5
  - 2.3.4
  - 2.3.4-clang
  - 2.3.3
  - 2.3.2
  - 2.3.1
  - 2.3.1-clang
  - 2.3.0
  - 2.3.0-preview2
  - 2.3.0-preview2-clang
  - 2.3.0-preview1
  - 2.3.0-preview1-clang
  - 2.2.0
script:
  - rspec
